// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceSystemv2.Infraestrutura.Data;

#nullable disable

namespace SpaceSystemv2.Infraestrutura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241219185135_ADD initial commit")]
    partial class ADDinitialcommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceSystemv2.Domain.Astronaut", b =>
                {
                    b.Property<Guid>("ID_Astronaut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Astronaut_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ID_AstronautRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_SpaceStation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReadyforLaunch")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Astronaut");

                    b.HasIndex("ID_AstronautRole");

                    b.HasIndex("ID_SpaceStation");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.AstronautRole", b =>
                {
                    b.Property<Guid>("ID_AstronautRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AstronautRole_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_AstronautRole");

                    b.ToTable("AstronautRoles");

                    b.HasData(
                        new
                        {
                            ID_AstronautRole = new Guid("1e5fb4cd-c7fb-478a-97d1-b318b642e258"),
                            AstronautRole_Name = "Commander"
                        },
                        new
                        {
                            ID_AstronautRole = new Guid("c36a08b3-bf89-470c-b5da-8b4545555952"),
                            AstronautRole_Name = "Engineer"
                        },
                        new
                        {
                            ID_AstronautRole = new Guid("a097c251-44cc-4992-98c4-2065e1036171"),
                            AstronautRole_Name = "MissionSpecialist"
                        },
                        new
                        {
                            ID_AstronautRole = new Guid("20651e3e-b208-47b8-bd4b-cbe45d1d726e"),
                            AstronautRole_Name = "Pilot"
                        });
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Deploy", b =>
                {
                    b.Property<Guid>("ID_Deploy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Astronaut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Mission")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Rocket")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID_Deploy");

                    b.HasIndex("ID_Astronaut");

                    b.HasIndex("ID_Mission");

                    b.HasIndex("ID_Rocket");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Mission", b =>
                {
                    b.Property<Guid>("ID_Mission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ID_MissionType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MissionDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mission_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_Mission");

                    b.HasIndex("ID_MissionType");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.MissionType", b =>
                {
                    b.Property<Guid>("ID_MissionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MissionType_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_MissionType");

                    b.ToTable("MissionTypes");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Rocket", b =>
                {
                    b.Property<Guid>("ID_Rocket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rocket_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Rocket");

                    b.ToTable("Rocket");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.SpaceStation", b =>
                {
                    b.Property<Guid>("ID_SpaceStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CrewCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InaugurationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpaceStation_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_SpaceStation");

                    b.ToTable("SpaceStations");

                    b.HasData(
                        new
                        {
                            ID_SpaceStation = new Guid("9fc58dd5-cc9c-4780-954c-92db908a4568"),
                            CrewCapacity = "255",
                            InaugurationDate = "11/12/2024",
                            SpaceStation_Name = "ISS"
                        });
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.SpaceTourismStation", b =>
                {
                    b.Property<Guid>("ID_SpaceTourismStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpaceTourismStation_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TouristCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TouristsPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SpaceTourismStation");

                    b.ToTable("SpaceTourismStations");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Astronaut", b =>
                {
                    b.HasOne("SpaceSystemv2.Domain.AstronautRole", "AstronautRole")
                        .WithMany()
                        .HasForeignKey("ID_AstronautRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceSystemv2.Domain.SpaceStation", "SpaceStation")
                        .WithMany()
                        .HasForeignKey("ID_SpaceStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AstronautRole");

                    b.Navigation("SpaceStation");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Deploy", b =>
                {
                    b.HasOne("SpaceSystemv2.Domain.Astronaut", "Astronaut")
                        .WithMany()
                        .HasForeignKey("ID_Astronaut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceSystemv2.Domain.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("ID_Mission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceSystemv2.Domain.Rocket", "Rocket")
                        .WithMany()
                        .HasForeignKey("ID_Rocket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Mission");

                    b.Navigation("Rocket");
                });

            modelBuilder.Entity("SpaceSystemv2.Domain.Mission", b =>
                {
                    b.HasOne("SpaceSystemv2.Domain.MissionType", "MissionType")
                        .WithMany()
                        .HasForeignKey("ID_MissionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionType");
                });
#pragma warning restore 612, 618
        }
    }
}
